### ISSUE TITLE
Hi 😄 Here I will  add any issue I may face in work through with Open Science Community Saudi Arabia (OSCSA)

### ISSUE THREAD

**Issue by nancyalaswad90** [Open-Science-Community-Saudi-Arabia/localisation#2]
.

### Hi there <img src="https://raw.githubusercontent.com/ABSphreak/ABSphreak/master/gifs/Hi.gif" width="30px"></h2> 

# **First , I will introduce myself to my great team 😄**

=============================================================
.

>  **I'm  Nancy**  , [Master Accountant](https://github.com/nancyalaswad90/nancyalaswad90/blob/master/%D8%A7%D9%84%D8%AC%D8%A7%D9%85%D8%B9%D8%A7%D8%AA.pdf) with more than 11 years experience working in Bank on operational & extracting data, And now she is working in AI, ML, DL, DS fields 

.

Now a days I am studying  [Information Technology and Computing](https://github.com/nancyalaswad90/nancyalaswad90/blob/master/second%20.md)  at Arab Open University as second Bachelor  study path and  [Medical Laboratory](https://github.com/nancyalaswad90/Medical-Laboratory/blob/main/README.md)   diploma college as third  study path.

That's why I'm excited to contribute this summer with you and I have chosen the **Open Science Community Saudi Arabia (OSCSA)** cause  [Localization](https://www.vengaglobal.com/blog/translation-localization-difference/) **project** will give me a good experience  and [as defined by Stephanie Harris.](https://www.vengaglobal.com/blog/translation-localization-difference/)

 [Localization](https://www.vengaglobal.com/blog/translation-localization-difference/)  **is a more comprehensive process than translation** that addresses cultural and non-textual components as well as linguistic issues when adapting the text for another country or locale.

.

> **So , my aim is to gain ideas about `Localization` and use it in my study progresses and knowledge `then` share the advantages with others** 

.

### I hope that acceptable 😄

.

**Comment by nancyalaswad90** [comment]
.

> **Hi** @BatoolMM 


Please support , I got this issue where I cant find any translator to work with , Am I losing idea ???





.

![Capture](https://user-images.githubusercontent.com/36210723/160545174-5c6b4d7a-de4f-4161-a7f2-e0866645edbc.PNG)

**Comment by BatoolMM** [comment]
Hi Nancy, thank you for your question. 
This's because you clicked on `Translation`, you are supposed to click on `go to editor

<img width="1196" alt="Screenshot 2022-03-29 at 09 58 55" src="https://user-images.githubusercontent.com/53487593/160552122-86187593-83f4-46c4-a5e9-04a2aac7a435.png">
`
Can you kindly add all your questions under the same issue #1, please?
