### ISSUE TITLE
Review Final applicants in Outreachy spring 2022 

### ISSUE THREAD

**Issue by BatoolMM** [Open-Science-Community-Saudi-Arabia/localisation#9]
This task is related to #1 to provide final feedback for all applicants who translated a significant part or made a PR. Anyone who submits a PR until the 22nd of April/or submitted a final contribution in Outreachy will be added to the list.

| Name              	| Submitted Final Contribution 	| Rename Files 	| Translation in Crowdin 	| Time Commitment 	| PR      	|
|-------------------	|------------------------------	|--------------	|------------------------	|-----------------	|---------	|
| @AsmaKacem1       	|    &check;     |       &check;  |     2426	|   89 / 88 days   	| &check; 	| 
| @Boutainaelatbaoui  	|  &check;                            	|     &check;           	|                    1239  	|               89 / 88 days  	| &check; 	|
| @nancyalaswad90   	| &check;                      	|           	|         228               	|            89 / 88 days     	| &check; 	|
| @ThanaMeri        	|    &check;                          	|      &check;        	| 1048                       	|            89 / 88 days     	| &check; 	|
| @amj1337          	| &check;   |    &check;     |     2645   	|         69% of their time	| &check; 	|
| @Muluh            	| &check;                      	|              	|    713                    	|            89 / 88 days     	|         	|

@AsmaKacem1 @ThanaMeri @Boutainaelatbaoui You submitted a partial application in Outreachy. Can you submit the final application through [this link](https://www.outreachy.org/outreachy-may-2022-internship-round/communities/open-science-community-saudi-arabia-oscsa/localisation-of-open-educational-resources-of-open/contributions/), please?

**Comment by Boutainaelatbaoui** [comment]
Hello @BatoolMM  could you help me with this?

**Comment by ThanaMeri** [comment]
I completed mine. it was a pleasure working with you @BatoolMM

**Comment by BatoolMM** [comment]
Thank you to everyone who submitted their final application 🎉 🎉 . Can I ask everyone one more thing which is to create a simple PR and rename the file you created for docs as follow `NAME_review.md` e.g. (`Asma_review.md`, `Thana_review.md`, `nancy_review.md`, Boutaina_review.md, ..etc). We just want to rename the file you called previously `docs.md` with your name then underscore `review`. Can you possibly do that?
